### ISSUE TITLE
[FlurryDataSender retransmitNotSentBlocks] Crash

### ISSUE THREAD

**Issue by jstart** [flurry/FlurryIntegrationSamples-iOS#1]
Hey there,
Not sure if this is the right place to report issues with the SDK but we are seeing a serious crash in eHarmony.  Other people are reporting this issue in detail:

https://github.com/AntonPalich/Flurry/issues/36
http://stackoverflow.com/questions/30242618/flurry-retransmitnotsentblocks-crash/30723000#30723000
eHarmony Crashlytics Report: http://crashes.to/s/5e47302e35e
![screenshot 2015-06-18 14 19 44](https://cloud.githubusercontent.com/assets/108218/8242565/1d567e88-15c5-11e5-80f4-8f4e86d54ce8.png)

**Comment by flurrydev** [comment]
We are aware of this crash.  It happens occasionally when the device that was previously off line attempts to send the session data to the Flurry servers. The team is working to fix it, we are expecting the update to be released around 6/26.

**Comment by phamquy** [comment]
any update on this ?

**Comment by jstart** [comment]
@phamquy It seems like this crash is gone in v6.6.0 of the sdk

**Comment by niklassaers** [comment]
It is very much still there in 6.6.0

**Comment by ugonna** [comment]
Closing this ticket now as this issue had indeed been resolved since 6.6.0.
