### ISSUE TITLE
No render time ad received for this space

### ISSUE THREAD

**Issue by antongaenko** [flurry/FlurryIntegrationSamples-iOS#6]
Hi! 
Sometimes ads are shown, but sometimes I got Error Domain=FlurryAds Code=104 "FlurryAds: No render time ad received for this space." and nothing happens. 
What does it mean?

**Comment by ugonna** [comment]
The error code 104 is shown when there are no ads available for the ad space at the current time and location. It should just be a fill-rate issue and is heavily dependent on the ad demand available in your location.

If you have concerns with the fill-rate in your app, please contact support@flurry.com.

**Comment by antongaenko** [comment]
Thank you for quick response!

**Comment by IAmMonika** [comment]
@Just-
I got this error FlurryAds: No ads available from server for this space." UserInfo={NSLocalizedDescription=FlurryAds: No ads available from server for this space.}]
