### ISSUE TITLE
Error Domain=FlurryAds Code=104 "FlurryAds: No ads available from server for this space.

### ISSUE THREAD

**Issue by KPPraveen** [flurry/FlurryIntegrationSamples-iOS#7]
Hi! 
I have created an app universal ios app in Flurry.com and created a native adSpace. Given the API key and adSpace name as described in the documentation.  But I got Error when i run the app and nothing happens. Error log is Given below
 Load AdUnit Timed out
Picked cached ad unit 0x0 with guid (null)
Successfully parsed ad request schema
Successfully created ad request.
 Sending AdRequest....
 Sending AdRequest of size 1224....
Flurry: HTTP connection delegate received response[<NSHTTPURLResponse: 0x1a948870> { URL: https://ads.flurry.com/v14/getAds.do } { status code: 200, headers {
    Connection = "keep-alive";
    "Content-Length" = 78;
    "Content-Type" = "application/octet-stream";
    Date = "Wed, 04 May 2016 05:20:08 GMT";
    "FM-Checksum" = "-909430395";
    "Keep-Alive" = "timeout=10";
    Server = nginx;
} }]
 This is a ad response of len 78
 Successfully parsed ad response schema
 Error in AdRequest: [Database has no section id for ad space]
 FlurryAdCache: skipping adunit with empty or nil adspace
******\* logAdEvent:     *\* [<FlurryAdEvent: 0x1aa517f0> unfilled(4), T:28460] 
 *\* <FlurryAdLog: 0x186d08b0> [S:1462339177513, RS:1462339177513 ID:1, GUID (null), {(
    "    *\* [<FlurryAdEvent: 0x1aa517f0> unfilled(4), T:28460] "
)} transmitted {{
}} ]**

---

  Native Ad for Space [FlotillaNative1] Received Error # [1], with description: [Error Domain=FlurryAds Code=104 "FlurryAds: No ads available from server for this space." UserInfo=0x1a94a070 {NSLocalizedDescription=FlurryAds: No ads available from server for this space.}]  ================ 
What does it mean?

**Comment by rollinsio** [comment]
Hi @KPPraveen, let's take this to support@flurry so that they can give you a hand.

**Comment by IAmMonika** [comment]
@rollinsio 
I got this error
FlurryAds: No ads available from server for this space." UserInfo={NSLocalizedDescription=FlurryAds: No ads available from server for this space.}]

**Comment by KPPraveen** [comment]
Hi,
I got the ads after 1 day creating the ad id in flurry account. You will
receive the ads only after the ad Id you have created is added to their db.

**Comment by IAmMonika** [comment]
@KPPraveen  But I also get this error **Error in AdRequest: [Ad request view type doesn't match ad space placement]**
today is  second day after creation of project and adspace in flurry

**Comment by rollinsio** [comment]
@patelmonika006 let's move this to integration @ flurry.com.  

Regards,

Mike
