### ISSUE TITLE
Video ads is not dispalyed

### ISSUE THREAD

**Issue by IAmMonika** [flurry/FlurryIntegrationSamples-iOS#8]
Native video ads is not display. It gives error  Native Ad for Space [LaAdictiva Video Stream] Received Error # [1], with description: [Error Domain=FlurryAds Code=117 "FlurryAds: Ad request to server failed." UserInfo={NSLocalizedDescription=FlurryAds: Ad request to server failed.}]

**Comment by IAmMonika** [comment]
Please check my error and give me some solution to solve
Thanks

**Comment by rollinsio** [comment]
Please don't spam all of the closed topics.  You can write in to integration @ flurry.com and we will handle it there.

**Comment by IAmMonika** [comment]
I already mail on flurry.com
But I did not get any response

**Comment by rollinsio** [comment]
Yes, yesterday.  Please be patient, we will get to you.  But spamming github is not a great way to make any support team happy about answering your question.

To elaborate, there are probably no ads where you are at this time.  You should invoke test ads and you should start seeing ads.
